### ISSUE TITLE
'ERROR: Command errored out with exit status 1: python setup.py egg_info.' while installing

### ISSUE THREAD

**Issue by LaoshuBaby** [enzet/map-machine#111]
Hello, I'm running `pip install .` in my WSL (because I can't change my windows py version from 3.10, and 3.10 will occur #101 's ERROR) 

But this time meet with those problem:

![图片](https://user-images.githubusercontent.com/42690037/153192938-98978a98-b0dd-45d2-b738-4df5c886ee4f.png)

```
root@LAOSHU-LAPTOP:/data/map-machine# pip install .
Processing /data/map-machine
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dx27l95w/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dx27l95w/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-dx27l95w/pip-egg-info
         cwd: /tmp/pip-req-build-dx27l95w/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dx27l95w/setup.py", line 7, in <module>
        from map_machine import (
      File "/tmp/pip-req-build-dx27l95w/map_machine/__init__.py", line 16, in <module>
        REQUIREMENTS: list[str] = [
    TypeError: 'type' object is not subscriptable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

What wrong had I made?

**Comment by enzet** [comment]
Hello @LaoshuBaby!

Thank you for reporting! Sorry, I can only take a look in a few hours.

**Comment by enzet** [comment]
@LaoshuBaby, could you please check Python version inside WSL? Seems like it's less than 3.9.

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/153330660-da599904-6724-4d88-a724-94f2db6ed1e7.png)

Oops, this time is also my falut, I only check my host devices' version higher ...

I'll try to set a exact 3.9 python environment to retry your work. Sorry for bother everyone!

**Comment by enzet** [comment]
That's totally OK. It is error message that is confusing. I should add checking for Python version with more human-readable diagnostics.

**Comment by LaoshuBaby** [comment]
I wrote this problem in my https://github.com/LaoshuBaby/map-machine-cookbook

I'm still meet with plenty of mistake, and heven't successful rendered any image

:(

**Comment by enzet** [comment]
Hello, @LaoshuBaby! I'm very sorry for the late reply. I fell off the grid.

Thank you for the great Q&A repository!

Are your questions still relevant? Could you please describe problems?
