### ISSUE TITLE
better handling of bbox parameter starting with a minus

### ISSUE THREAD

**Issue by Strubbl** [enzet/map-machine#113]
Bbox coordinates starting with a negative value result in a failing map machine render process, e.g. the giving the bbox
`-b -57.5609702111,-38.0083456336,-57.5300067903,-37.9922146273` as parameter does not create a map.

I get the following error then:
```
$ map-machine render --cache /maps/cache -z 14 -o /maps/test.svg -b -57.5609702111,-38.0083456336,-57.5300067903,-37.9922146273
usage: map-machine render [-h] [-i [<path> ...]] [-o <path>]
                          [-b <lon1>,<lat1>,<lon2>,<lat2>] [--cache <path>]
                          [-z <float>] [-c <latitude>,<longitude>]
                          [-s <width>,<height>] [--buildings <mode>]
                          [--mode <string>] [--overlap <integer>]
                          [--labels <string>] [--level LEVEL]
                          [--seed <string>] [--tooltips | --no-tooltips]
                          [--country COUNTRY]
                          [--ignore-level-matching | --no-ignore-level-matching]
                          [--roofs | --no-roofs]
map-machine render: error: argument -b/--boundary-box: expected one argument
```

This error can be worked around when i leave out the space between the parameter and the bbox, e.g. `-b-57.5609702111,-38.0083456336,-57.5300067903,-37.9922146273`

**Comment by Strubbl** [comment]
It gets even worse if you use the bbox `-23.0016,-67.7356,-23.0415,-67.7576`:

```
$ map-machine render --cache /maps/cache -z 17 -o /maps/test.svg -b-23.0016,-67.7356,-23.0415,-67.7576
CRITICAL Negative horizontal boundary.
CRITICAL Specify either --input, or --boundary-box, or --coordinates and --size.
```

**Comment by enzet** [comment]
Hello, @Strubbl!

Just two days ago discussed this with @Eiim. Please take a look at his issue #109.

In #110 I've added even more notes to the readme and help message. But not sure whether this make things clearer or more confusing.

**Comment by Strubbl** [comment]
Thanks for the hint. I was searching the issues for the word longitude only, so that i have not seen #109
