### ISSUE TITLE
Finish installation instructions

### ISSUE THREAD

**Issue by berrely** [enzet/map-machine#115]
Currently, the install section of the readme is practically empty. This should ideally be filled.

**Comment by enzet** [comment]
Hi @berrely! Thank you for reporting!

Could you please explain what exactly do you want to see in the Install section? I just wanted to left it as short as possible to make things simple.

**Comment by berrely** [comment]
> Hi @berrely! Thank you for reporting!
> 
> Could you please explain what exactly do you want to see in the Install section? I just wanted to left it as short as possible to make things simple.

Well ideally they'd have all the Python packages you need (listed in the packages file) and instructions on how to download and install on different operating systems, but even basic installation steps would be useful.

**Comment by enzet** [comment]
`pip install .` will do just everything needed for the Python part: it will install required packages and make `map-machine` available from the command line. Two listed libraries have pretty nice installation steps on their sites for all operating systems. So I believe strictly speaking the Installation section is fine and I really don't want to enlarge it.

Maybe it's good idea to create additional `INSTALL.md` file with ultimate list of steps for each operating system starting from installation of Python and pip? And add a link to it from the readme?

**Comment by berrely** [comment]
That would be very useful. Something like "For installation instructions, see INSTRUCTIONS.md"

**Comment by enzet** [comment]
Thank you! I'll try to write this at least for Ubuntu and macOS.

**Comment by enzet** [comment]
Hello @berrely! Could you please take a look at pull request #116, does it make things more clear?

**Comment by sikmir** [comment]
Just in case, there is a [package](https://github.com/sikmir/nur-packages/blob/master/pkgs/osm/map-machine/default.nix) for NixOS.

**Comment by enzet** [comment]
> Just in case, there is a [package](https://github.com/sikmir/nur-packages/blob/master/pkgs/osm/map-machine/default.nix) for NixOS.

Wow, this is great! Thank you!

May I refer to it from the `INSTALL.md` file?

**Comment by sikmir** [comment]
> May I refer to it from the `INSTALL.md` file?

Yes, but it's NUR repository, it's not submitted to [nixpkgs](https://github.com/nixos/nixpkgs), since map-machine is not released yet.

**Comment by berrely** [comment]
> Hello @berrely! Could you please take a look at pull request #116, does it make things more clear?

Yep, looks great. It would be nice if there were instructions how to run it as well, but this is great regardless. Thanks!

**Comment by enzet** [comment]
Right.

> since map-machine is not released yet.

Shame on me. I should have done this long ago.

**Comment by enzet** [comment]
Great!

> It would be nice if there were instructions how to run it as well, but this is great regardless.

Yes, I'll gradually expand usage section in the future.

Thank you!
