### ISSUE TITLE
Draw railways under construction

### ISSUE THREAD

**Issue by Zero3** [enzet/map-machine#125]
This would be useful in my opinion. OSM shows them as well.

Example: https://www.openstreetmap.org/way/926175220

**Comment by enzet** [comment]
Hello, @Zero3. Do you think this is fixed?

**Comment by Zero3** [comment]
Seems like you did not update the `python3.8` branch with the change, but I copy-pasted it in manually on my machine, and it looks pretty nice.

However, the railways under construction now look more prominent than the already built railways. The under construction ones are darker and wider. I think the widths should be similar instead, and the existing railways at least as dark as the ones under construction.

**Comment by Zero3** [comment]
Forget the last part of my comment above. I applied the change incorrectly to my local config at first.

New thoughts: Looks pretty good overall. However, they are drawn beneath roads and buildings, which looks a bit odd (note that I made building a bit transparant in this screenshot - normally they are solid):

![image](https://user-images.githubusercontent.com/82504/165855411-50aab12f-878d-4e6e-98ba-6b552bd27279.png)

I would prefer if they were drawn on top, I think? Also, I think `stroke-dasharray: 15,5` would be a bit better. I think longer strokes make it look more intuitive:

![image](https://user-images.githubusercontent.com/82504/165856052-8da1674e-c843-4034-b7f8-34e5e82f5429.png)

Perhaps reducing the width `2` instead of `3` could be considered too.

Anyway, these are just suggestions. I will let you figure out what you want to go with :).

**Comment by enzet** [comment]
Hi, @Zero3!

Yes, I think rails should definitely go above roads. However I'm not sure about buildings. I sometimes make building layer transparent too. Probably, there should be a command line options for this.

Size of dashes was quite arbitrary, your suggestion looks better.

**Comment by enzet** [comment]
I want to fix what we have for now and then decide what kind of overlapping we want for roads and railroads.

This is Map Machine rendering for now:

![overlap](https://user-images.githubusercontent.com/2399987/170842280-d7717568-fa89-4c30-8852-a92af7e9be19.png)

**Comment by enzet** [comment]
After 
  - styles for disused and abandoned railways (a6c94a0), 
  - and the priority splitting (d0ef85c):

![overlap](https://user-images.githubusercontent.com/2399987/171064515-ac4b51c2-9d82-4d63-949b-df50a490d810.png)

**Comment by enzet** [comment]
Hope this issue is done.  Feel free to reopen it if I'm wrong.
