### ISSUE TITLE
waterway=river is hidden behind natural=wood

### ISSUE THREAD

**Issue by Zero3** [enzet/map-machine#126]
Example: https://www.openstreetmap.org/way/258695030

Can be fixed by setting priority to `22`, since `natural=wood` has priority of `21`. I did not consider if the priority should be even higher.

**Comment by enzet** [comment]
You're right. Thank you.

**Comment by enzet** [comment]
I set the priority of waterways to 22. But I really don't like this priority solution. Really counter-intuitive. I have to refactor this or at least add some checks.

_Notes for me_: command is `map-machine render -c 55.43238,10.29241 -s 800,600`

**Comment by enzet** [comment]
Hi, @Zero3! I've added a test for this, so as not to break the order if I want to refactor priority.

Could you please close this issue if you think it's done.

**Comment by Zero3** [comment]
Thanks. I will have a look once these changes arrive in the `python3.8` branch.

**Comment by enzet** [comment]
Hi, @Zero3! Sorry for the late response. I've updated the branch, fixed Python version in documentation, and increased the project version. Could you please take a look and tell me if I forgot something.

**Comment by Zero3** [comment]
No worries! Thanks for the fix. I will check it when I get back to my map project. It might take a little while, but I will make sure to check it once I get back to it! :)

**Comment by enzet** [comment]
Hope this issue is done.

**Comment by Zero3** [comment]
Sorry I did not get time to re-test this in a reasonable timeframe. Good idea to close this - I can always create a new issue if I run into the problem again :+1:. Thanks again for fixing.
