### ISSUE TITLE
Most vending machines rendering with generic icon

### ISSUE THREAD

**Issue by Cguy7777** [enzet/map-machine#132]
It appears that the generic vending machine icon is taking precedence over more specific ones when `amenity=vending_machine` is present.

For example, the icon for a drink vending machine appears when tagged with just `vending=drinks`, but the generic icon is drawn with both `amenity=vending_machine` and `vending=drinks` (the recommended tagging).

Exception: Excrement bag dispensers are rendering properly.

**Comment by enzet** [comment]
Hi, @Cguy7777!

Thank you for the report! This is definitely a bug. I'll change tag priority.
