### ISSUE TITLE
Icons - Add tracks to tramway (like train)

### ISSUE THREAD

**Issue by chatelao** [enzet/map-machine#134]
Trams would be nicer with tracks (like the trains) to be distinguished from buses.

**Comment by enzet** [comment]
Hi, @chatelao!

Sorry if I've got it wrong. Which tag do you mean exactly? It looks like `railway=tram` is supported.

![overlap](https://user-images.githubusercontent.com/2399987/176139070-feb2fe03-875e-42a6-870e-7d360595c144.svg)

**Comment by enzet** [comment]
@chatelao, feel free to reopen if I got it wrong.
