### ISSUE TITLE
New Tagged Version

### ISSUE THREAD

**Issue by Unkn0wnCat** [enzet/map-machine#146]
Hey,

love the project! I'm trying to bring it to NixOS, and I've noticed a lot has changed since the last tagged version was created.

Is it possible to add a new tag with the up-to-date source?

Thanks in advance,
Kevin

**Comment by enzet** [comment]
Hi, @Unkn0wnCat!

Sorry, my bad.

**Comment by enzet** [comment]
Done! It's 0.1.8 now.
